-- =====================================================
-- JimuReport 数据集 - 核心指标概览（数字卡片）
-- 说明: 已拆分为 01a~01d 四个独立 SQL，每个 KPI 对应一个数据集
-- 请使用: 01a_kpi_total_sale.sql / 01b_kpi_total_profit.sql
--        01c_kpi_profit_rate.sql / 01d_kpi_stock_amount.sql
-- =====================================================
